---
- name: Restart openvpn
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/openvpn-server/"
    build: false
    restarted: true
  become: false

- name: Restart monitoring
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/monitoring/"
    build: false
    restarted: true
  become: false